githubRepoOwner: srpande
githubRepoName: spr
githubHost: github.com
githubRemote: origin
githubBranch: master
requireChecks: false 
requireApproval: false
mergeMethod: squash
mergeQueue: false
forceFetchTags: false
