githubRepoOwner: srpande
githubRepoName: sirish
githubHost: github.com
githubRemote: origin
useLocalBranchName: true
githubBranch: master
requireChecks: false 
requireApproval: false
mergeMethod: squash
mergeQueue: false
forceFetchTags: false
